In [6]:
import pandas as pd
import numpy as np
import os
# from pandas_profiling import ProfileReport
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
wh = pd.read_csv('https://www.cs.helsinki.fi/u/jttoivon/dap/data/fmi/kumpula-weather-2017.csv')
wh

,Year,m,d,Time,Time zone,Precipitation amount (mm),Snow depth (cm),Air temperature (degC)
0,2017,1,1,00:00,UTC,-1.0,-1.0,0.6
1,2017,1,2,00:00,UTC,4.4,-1.0,-3.9
2,2017,1,3,00:00,UTC,6.6,7.0,-6.5
3,2017,1,4,00:00,UTC,-1.0,13.0,-12.8
4,2017,1,5,00:00,UTC,-1.0,10.0,-17.8
...,...,...,...,...,...,...,...,...
360,2017,12,27,00:00,UTC,1.1,-1.0,3.8
361,2017,12,28,00:00,UTC,3.7,-1.0,2.8
362,2017,12,29,00:00,UTC,7.8,-1.0,3.8
363,2017,12,30,00:00,UTC,4.1,-1.0,2.5
364,2017,12,31,00:00,UTC,3.2,-1.0,1.6

In [4]:
#problem 10
wh[wh['m']==7]['Air temperature (degC)'].mean()

16.035483870967745

In [7]:
# problem 11
wh[wh['Air temperature (degC)']<0]['Year'].count()

Year                         49
m                            49
d                            49
Time                         49
Time zone                    49
Precipitation amount (mm)    49
Snow depth (cm)              49
Air temperature (degC)       49
dtype: int64